[build]
  # Este comando no es estrictamente necesario si no tienes un paso de construcción,
  # pero es una buena práctica.
  command = "echo 'No build command required'"

[functions]
  # Le decimos a Netlify que nuestras funciones están en la carpeta "netlify/functions"
  directory = "netlify/functions"