name = "core"
main = "workers/router/index.js"
# main = "workers/api/api.js"
compatibility_date = "2024-01-01"

# ------------------------------------------------------------
# KV Namespace
# ------------------------------------------------------------
[[kv_namespaces]]
binding = "AREA51_KV"
id = "b6330a5ca2b6489da5e06e73ff54f4d8"

# ------------------------------------------------------------
# Triggers para eventos programados (Cron Jobs)
# ------------------------------------------------------------
[triggers]
crons = ["00 03 * * *"] # Se ejecutará todos los días a las 3:00 AM UTC
